### ISSUE TITLE
Text version in parallel with the graphical blocks ? (discussion)

### ISSUE THREAD

**Issue by cocofifi** [walterbender/turtleblocksjs#338]
I'm not sure this is the right place to ask this question, so feel free to close the issue or move it to a wiki or a discussion forum. While trying to show my 9 years old son how turtleblocks works, I became quickly annoyed by the space requirements for the blocks on the screen. With a few functions and a few color changes, for example, or adding only 2 or 3 variables, the screen becomes quickly full of blocks. I would like to know if you plan to have the possibility of associating the blocks with a text representation of the script. It could be more compact, easier to debug and maybe easier to follow if more than a few blocks are used. 

In the days of Borland Delphi, visual programming was used to design the interface of a program, but the developer always had access to the underlying function and object calls and parameters. Maybe I'm just melancholic about that interface, but I always found it natural and productive.

Many thanks for developing the turtleblocks. Best regards.

**Comment by walterbender** [comment]
A few comments:
(1) In the Python version of Turtle Blocks, you can export your project as Logo or Python code. I have not added a similar feature to the JS version yet.
(2) I am not 100% certain if I follow what you are asking for as I never programmed in Delphi, but the way I typically work is to make use of action blocks. Putting code into an action clamp essentially allows you to define a macro (the stack of blocks is represented by a new block which can be used like any other block). The action stack itself can be collapsed to save screen space. Does that serve the general purpose?

**Comment by walterbender** [comment]
(3) Also, there is an eval block in the Python version, which can be used to run code as text. I meant it primarily as a quick way to extend the language, esp. math functionality. I disabled it in the JS version since it struck me as a security risk. Easy enough to enable for your own use (just set hidden=false in basicblocks.js
(4) Writing plugins to extend Turtle is pretty easy and documented on github in the repo.
(5) There is a somewhat obscure feature: if you long press on an action, you are given the option to save it to personal palette. This way you can save common macros between projects.

**Comment by cocofifi** [comment]
Many thanks for all these information. Will definitely explore the options you mentioned.
