### ISSUE TITLE
New Version TB 1

### ISSUE THREAD

**Issue by jaskirat2000** [walterbender/turtleblocksjs#355]
![image3](https://user-images.githubusercontent.com/10228651/37262985-1b5d19b0-25cc-11e8-915a-a1a32c6a88d4.jpg)
![image2](https://user-images.githubusercontent.com/10228651/37262987-1b95ed3a-25cc-11e8-878f-61d75fae5d34.jpg)
![image1](https://user-images.githubusercontent.com/10228651/37262988-1bd783da-25cc-11e8-9d16-9a3a6cdd680e.jpg)

Well, Here i have made two designs named as image1 and image2 (image3 is a part of
image2) the features i have added are :
1. Firstly, changing the UI/UX color(Black and grey)
2. Making the palette icon in two column.In image one colored and in
image 2 it is in grey in color so when a user will click on any
particular icon then that will get colored and will show all its
blocks ( as shown in image3)
3. Added a search bar where a user can find the blocks if not able to get.
4. Added a need help option where full programme guidelines can be seen offline.
5. Added a preview window to the left side of screen, so that it don't
get houch-pouch in coding and drawing area but that preview window can
be maximize with one click button.
6. Made a colors light of all blocks and made changes in the names of it.
7. Added a feature of adding a new window in it.

**Comment by walterbender** [comment]
Maybe it is best to break this down into a series of separate feature requests?

1. color scheme. There is an open ticket regarding making the color scheme configurable.
https://github.com/walterbender/musicblocks/issues/714

2a. Making the palette icons into two columns.
https://github.com/walterbender/musicblocks/issues/822

2b. Making the utility buttons multicolumn (presumably to make room fot the thumbnail)

2c. Changing the behavior of the utility buttons in regard to color.

3. Move the search bar from the utility panel to the main toolbar.

4. Make the guide available from the help panel

5. Add a thumbnail preview window.

6. Change the block colors (See https://github.com/walterbender/musicblocks/issues/714).

7. I don't understand this one: "Added a feature of adding a new window in it."

It would also be helpful to have some explanation as to why these features are being requested along the lines of https://wiki.sugarlabs.org/go/Features/Policy (We are using github issues for features rather than the wiki).

**Comment by jaskirat2000** [comment]
The plus sign "+" , green in color written with Turtle Blocks 1 is the new window option

**Comment by walterbender** [comment]
What does "new window option" mean in this context?

**Comment by walterbender** [comment]
This issue is redundant with the individual issues:

#358 #359 #360 #362 #363 #364
